name: "Security Vulnerability"
about: "Privately report a security vulnerability"
title: "[SECURITY] Short description"
labels: ["security"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Report vulnerabilities responsibly.**  
        If this vulnerability contains sensitive details, please email us at [security@yourcompany.com] rather than disclosing publicly here.
  - type: input
    id: summary
    attributes:
      label: "Vulnerability Summary"
      description: "Give a concise summary of the suspected vulnerability."
      placeholder: "Example: 'SQL injection possible in the login endpoint'"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Detailed Description"
      description: "Describe the vulnerability, steps to reproduce, potential impact, etc."
      placeholder: "Detailed explanation..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment / Context"
      description: "SaaS plan type, API endpoint, environment (prod/dev), etc."
      placeholder: "Any relevant environment details..."
  - type: textarea
    id: impact
    attributes:
      label: "Potential Impact"
      description: "What can a malicious actor achieve through this exploit?"
      placeholder: "E.g., data exfiltration, account takeover, etc."
  - type: textarea
    id: recommendation
    attributes:
      label: "Suggested Remediation"
      description: "If you have suggestions, describe how this vulnerability could be fixed."
      placeholder: "Proposed fix (if known)..."
  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Any logs, screenshots, or references to help us confirm the issue."
      placeholder: "Optional"
