services:
  docgen:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - python_cache:/root/.cache/pip
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_OWNER=${GITHUB_OWNER:-}
      - GITHUB_REPO=${GITHUB_REPO:-}
      - MCP_SERVER_PORT=7867
      - MCP_SERVER_HOST=0.0.0.0
      - COVERAGE_SERVER_PORT=7868
    ports:
      - "7867:7867"
      - "7868:7868"
    tty: true
    stdin_open: true
    networks:
      - docgen_network

volumes:
  node_modules:
  python_cache:

networks:
  docgen_network:
    driver: bridge