version: '3.8'

services:
  docgen:
    container_name: docker-docgen-1
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/app
      - /app/node_modules # Don't override node_modules in the container
    ports:
      - "3000:3000"  # Example port for a web server
      - "3001:3001"  # GitHub Issues MCP server
      - "3002:3002"  # Coverage Analysis MCP server
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # Keep container running