name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**/*.md'
      - 'docs/_templates/**/*.hbs'
      - 'scripts/**/*.js'
      - 'scripts/**/*.ts'
      - 'src/**/*.ts'
      - 'test/**/*.js'
      - 'test/**/*.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm test -- --coverage
      
      - name: Run linting
        run: npm run lint
      
      - name: Calculate test coverage
        id: coverage
        run: |
          COVERAGE=$(node -e "const fs=require('fs'); \
            const report=JSON.parse(fs.readFileSync('./coverage/coverage-final.json')); \
            const coverage=Object.values(report).reduce((acc, file) => { \
              return acc + file.covered / (file.covered + file.missed); \
            }, 0) / Object.keys(report).length * 100; \
            console.log(Math.round(coverage))")
          echo "::set-output name=percentage::$COVERAGE"
      
      - name: Comment PR with coverage info
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: test-coverage
          message: |
            ## Coverage Report
            Test coverage: ${{ steps.coverage.outputs.percentage }}%
            
            <details>
              <summary>Coverage Details</summary>
              
              ```
              $(cat ./coverage/lcov-report/index.html | grep -A 10 "<div class='fl pad1y space-right2'>")  
              ```
            </details>

  validate:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate documentation
        run: npm run validate
      
      - name: Report validation issues
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            const fs = require('fs');
            try {
              const report = JSON.parse(fs.readFileSync('docs/reports/validation.json', 'utf8'));
              const issues = report.issues || [];
              if (issues.length > 0) {
                const issueBody = issues.map(i => `- **${i.severity}**: ${i.message} in ${i.file}`).join('\n');
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## Documentation Validation Failed\n\n${issueBody}`
                });
              }
            } catch (error) {
              console.error('Error reading validation report:', error);
            }